// <auto-generated />
namespace TMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _initialCreate31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_initialCreate31));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131209276__initialCreate31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
